addressbook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
import contacts.views
from django.contrib import auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', contacts.views.ListContactView.as_view(),
        name='contacts-list',),
    url(r'^new$', contacts.views.CreateContactView.as_view(),
        name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(),
        name='contacts-edit',),
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),
        name='contacts-delete',),
    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),
        name='contacts-view',),
    url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),
    url('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/models.py
from django.db import models
from django.urls import reverse


from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class Contact(models.Model):

    first_name = models.CharField(
        max_length=255,
    )
    last_name = models.CharField(
        max_length=255,

    )

    email = models.EmailField()

    def get_absolute_url(self):
        return reverse('contacts-view', kwargs={'pk': self.id})

    def __str__(self):

        return ' '.join([
            self.first_name,
            self.last_name,
        ])


class Address(models.Model):

    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    address_type = models.CharField(
        max_length=10,
    )

    address = models.CharField(
        max_length=255,
    )
    city = models.CharField(
        max_length=255,
    )
    state = models.CharField(
        max_length=2,
    )
    postal_code = models.CharField(
        max_length=20,
    )

    class Meta:
        unique_together = ('contact', 'address_type',)

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from contacts.models import Contact, Address


class ContactForm(forms.ModelForm):

    confirm_email = forms.EmailField(
        label="Confirm email",
        required=True,
    )

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'confirm_email')

    def __init__(self, *args, **kwargs):

        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email

        super().__init__(*args, **kwargs)

    def clean(self):

        if (self.cleaned_data.get('email') !=
                self.cleaned_data.get('confirm_email')):
            raise ValidationError(
                "Email addresses must match."
            )

        return self.cleaned_data


ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
    fields=('address_type', 'address', 'city', 'state', )
)

contacts/views.py
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from contacts import forms
from contacts.models import Contact


class ListContactView(ListView):

    model = Contact
    template_name = 'contact_list.html'


class CreateContactView(LoginRequiredMixin, CreateView):

    model = Contact
    template_name = 'edit_contact.html'

    form_class = forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')

        return context


class UpdateContactView(LoginRequiredMixin, UpdateView):

    model = Contact
    template_name = 'edit_contact.html'
    fields = ('first_name', 'last_name', 'email')

    def get_context_data(self, **kwargs):
        print('update')
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-edit',
                                    kwargs={'pk': self.get_object().id})

        return context

    def get_success_url(self):
        return reverse('contacts-list')


class DeleteContactView(DeleteView):

    model = Contact
    template_name = 'delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')


class ContactView(DetailView):

    model = Contact
    template_name = 'contact.html'


class EditContactAddressView(UpdateView):

    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):

        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

contacts/templates/base.html
{% load staticfiles %}
<html>
  <head>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
  </head>

  <body>
   <div>
      {{ user }}
      {% if user.is_anonymous %}
      <a href="/accounts/login">login</a>
      {% else %}
      <a href="/accounts/logout">logout</a>
      {% endif %}
    </div>
    {% block content %}
    {% endblock %}

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

contacts/templates/contact.html
{% extends "base.html" %}

{% block content %}

<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

<ul>
{% for address in contact.address_set.all %}
   <li>{{ address.address }}<br/>
       {{ address.city }} {{ address.state }}<br/>
       {{ address.postal_code }}
   </li>
{% endfor %}
</ul>

{% endblock %}

contacts/templates/contact_list.html
{% extends "base.html" %}

{% block content %}
<h1>Contacts</h1>

<ul>
  {% for contact in object_list %}
    <li class="contact">
        <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
      (<a href="{% url "contacts-edit" pk=contact.id %}">edit</a>)
    </li>
  {% endfor %}
</ul>

<a href="{% url "contacts-new" %}">add contact</a>
{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Contact</h1>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url "contacts-delete" pk=contact.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "contacts-list" %}">No, cancel.</a>
</form>

{% endblock %}

contacts/templates/edit_addresses.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}"
      method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}

        <ul>
        {{ address_form.as_ul }}
        </ul>

    {% endfor %}

    <input type="submit" value="Save" />
</form>

{% endblock %}

contacts/templates/edit_contact.html
{% if contact.id %}
<h1>Edit Contact</h1>
{% else %}
<h1>Add Contact</h1>
{% endif %}

<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_ul }}
  </ul>
  <input id="save_contact" type="submit" value="Save" />
</form>
{% if contact.id %}
<a href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
{% endif %}
<a href="{% url "contacts-list" %}">back to list</a>